version: '3.7'

services:
  mariadb:
    container_name: mariadb.php-docker
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: password
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: unless-stopped
    tty: true
    user: "1000:1000"
    volumes:
      - ./mariadb/:/var/lib/mysql/

  nginx:
    container_name: nginx.php-docker
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    tty: true
    volumes:
      - ./src/:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/php-fpm.conf:/etc/nginx/php-fpm.conf
      - ./nginx/server.conf:/etc/nginx/server.conf
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/log/:/var/log/nginx/

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php.php-docker
    image: mccheesy/php
    restart: unless-stopped
    tty: true
    volumes:
      - ./src/:/var/www/
    working_dir: /var/www
