version: '3.6'

networks:
  bridge:
    driver: bridge

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    image: mccheesy/php
    networks:
      - bridge
    restart: unless-stopped
    tty: true
    volumes:
      - ./src/:/var/www/
    working_dir: /var/www

  mariadb:
    container_name: mariadb
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: password
    image: mariadb:latest
    networks:
      - bridge
    ports:
      - "3306:3306"
    restart: unless-stopped
    tty: true
    volumes:
      - ./mariadb/:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      - bridge
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    tty: true
    volumes:
      - ./src/:/var/www/
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/:/etc/nginx/ssl/
